// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE0U95g5-WN49B1X1yo10eaP6BST6uE_o',
    appId: '1:1092469922144:web:76bf0ff2d8cdbabc4ba605',
    messagingSenderId: '1092469922144',
    projectId: 'channil',
    authDomain: 'channil.firebaseapp.com',
    storageBucket: 'channil.appspot.com',
    measurementId: 'G-WTWZH4QVVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5s0tEy9EFGvYSEAlLf3pjpckwrOVsarQ',
    appId: '1:1092469922144:android:bd38d290fccc28184ba605',
    messagingSenderId: '1092469922144',
    projectId: 'channil',
    storageBucket: 'channil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBizCUQCBUErqnHcz8-xH0dqamRApIKgb8',
    appId: '1:1092469922144:ios:99fbcd853225e82c4ba605',
    messagingSenderId: '1092469922144',
    projectId: 'channil',
    storageBucket: 'channil.appspot.com',
    iosBundleId: 'com.example.channil',
  );
}
